### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by kvanderslice** [fiftyandfiftyorg/cll#3]

**Comment by wstecklair** [comment]
Mobile Design QA

- [ ] Nav when opened sticks to the top of the site no matter where you are on the page

- [ ] Research Theme Template: Headline/Title text runs a little too tight to the "more info" text
![image](https://user-images.githubusercontent.com/28412045/35351053-9a080bb4-00f4-11e8-8e95-1116d60755f4.png)

Honestly, that's it. You're doing a really great job. Feels like these QA sessions are getting shorter and easier for us (design team) because of your hard work. Keep it up!

**Comment by stutts** [comment]
Desktop QA - Google Chrome


Home - Faculty section

- [ ] This has probably already been addressed but the PSD (as well as the People page) says "Faculty" and on the live homepage it says "Faculty Members." Added it just in case.
![image](https://user-images.githubusercontent.com/14879336/35351112-cfff89f4-00f4-11e8-8a8e-95e42302c427.png)


Header

- [ ] This is just an idea but maybe if the bottom of the text in the header was (or even could be) aligned with the bottom of the menu "bar." It may help make the two elements work better together at different screen sizes.
![image](https://user-images.githubusercontent.com/14879336/35357339-1046c9ec-0108-11e8-828b-4aae65a0d58b.png)
 

*And to reinforce what Weston said, we really aren't having to do much of anything anymore in these QA's. Really nice job!
